### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by kingvision** [AlfredXiangWu/python_misc#1]
hi:
  i download your caffe code , and i use the caffe_ftr.py to extract feature. 
i got the error:
   ImportError: No module named _caffe
can you tell me how to fix it ?
thanks

**Comment by AlfredXiangWu** [comment]
Firstly, you need to set "caffe_root" in caffe_ftr,py. And then, you could do "make pycaffe"  and make sure it is complied successfully.

**Comment by kingvision** [comment]
yes, i had set the "caffe_root" in caffe_ftr.py. And i do "make pycaffe" ant it is successfully.'

but i still got the error! i put the caffe_ftr.py in the path/tp/caffe/build/tool .
is it ok?
thanks

**Comment by CLTFOREVER** [comment]
Dear Wu:
             i use the caffe_ftr.py to extract feature ,in your article,you said:the CPU time of extracting face feature vector based on CNN is nearly 67ms,but i nearly take 300ms with Titan x.Is there anything i do wrong? Can you tell me how to solve it?
thanks

**Comment by AlfredXiangWu** [comment]
@CLTFOREVER The python code is only used to extract features for evaluation. I implement a cnn lib via c++ and compare the CPU time of my model with the one of VGG model.
